title: Big Picture School
description: Using AI to teach the core principles of each major discipline for the purpose of encouraging interdisciplinary thought.
theme: just-the-docs

url: https://compoundingeffects.github.io/bigpictureschool


